repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        description: Runs Black auto-formatting
        entry: env PIPENV_PIPFILE=app/Pipfile pipenv run black --config=app/pyproject.toml
        files: .
        types: [python]
        language: system
        require_serial: true

      - id: isort
        name: iSort
        description: Runs isort to automatically sort imports alphabetically
        entry: env PIPENV_PIPFILE=app/Pipfile pipenv run isort --settings-path=app/setup.cfg
        files: .
        types: [python]
        language: system
        require_serial: true

      - id: mypy
        name: Mypy
        description: Runs Mypy static type checker
        entry: env PIPENV_PIPFILE=app/Pipfile pipenv run mypy --config-file=app/setup.cfg
        files: .
        types: [python]
        language: system
        require_serial: true

      - id: flake8
        name: Flake8
        description: Runs Flake8 static code analysis
        entry: env PIPENV_PIPFILE=app/Pipfile pipenv run flake8 --config=app/setup.cfg
        files: .
        types: [python]
        language: system
        require_serial: true
