# in our local dev env, we want:
#  - the app, auto-reloading, debug-level logs / messages
#  - linting / testing (which require both dev + prod deps)
#  - traefik
#  - redis
# and we need to be on both the internal service network, and the
# intra_service_network network so we can communicate with other services

version: "3.3"

services:
  app:
    build:
      context: "./app"
      args:
        BUILD_DEV: 1
    volumes:
      - ./app/:/usr/app/
    labels:
      - "service.name=liminus"
      - "traefik.docker.network=liminus_internal"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000 --no-server-header --no-date-header
    ports:
      - 5000
    networks:
      - liminus_internal
      - intra_service_network

  traefik:
    image: traefik:latest
    ports:
      - 8091:443
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/certs/local-liminus.crt:/etc/ssl/certs/public.crt
      - ./traefik/certs/local-liminus.key:/etc/ssl/private/private.key
    networks:
      liminus_internal:
      intra_service_network:
        aliases:
          - gatekeeper.liminus

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - liminus_internal

networks:
  liminus_internal:
  intra_service_network:
    external: true
