version: "3.3"

services:
  app:
    env_file: .env
    restart: unless-stopped
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.liminus.tls=true"
      - "traefik.http.routers.liminus.rule=HostRegexp(`{var:.*}`)"
      - "traefik.http.services.liminus.loadbalancer.server.port=5000"
      - "traefik.http.services.liminus.loadbalancer.server.scheme=http"
