version: "3.3"

services:
  app:
    env_file:
      - .env.locust
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000 --workers 3

  liminus-echo:
    build:
      context: "./echo-backend"
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    volumes:
      - ./echo-backend/:/usr/app/
    command: gunicorn echo:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000 --workers 5
    ports:
      - 5000
    networks:
      - internal